### ISSUE TITLE
bn.js: Cannot find module

### ISSUE THREAD

**Issue by dcbartlett** [bcoin-org/bstratum#1]
I keep getting this message when attempting to pull stratum in as a plugin.

```javascript
const node = new FullNode({
  network: "regtest",
  db: "memory",
  prefix: "/home/.bcoin",
  apiKey: "bikeshed",
  nodes: "127.0.0.1",
  port: 48444,
  env: true,
  logFile: true,
  logConsole: true,
  logLevel: "debug",
  workers: true,
  persistent: true,
  listen: true,
  plugins: [require("bcoin-stratum")]
});
```

```
Error: Cannot find module 'bcoin/node_modules/bn.js'
     at Function.Module._resolveFilename (module.js:536:15)
     at Function.Module._load (module.js:466:25)
     at Module.require (module.js:579:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/workspace/BcoinFarmer/node_modules/bcoin-stratum/lib/stratum.js:26:10)
     at Module._compile (module.js:635:30)
     at Object.Module._extensions..js (module.js:646:10)
     at Module.load (module.js:554:32)
     at tryModuleLoad (module.js:497:12)
     at Function.Module._load (module.js:489:3)
```

**Comment by tuxcanfly** [comment]
@dcbartlett make sure `bcoin-stratum`  dependencies are satisfied. You might need to do `npm install bcoin-stratum` from your bcoin repo.

**Comment by dcbartlett** [comment]
Sorry for the delay, Yes i have installed bcoin-stratum as you mentioned.  I get the error after installing it as such.
